### ISSUE TITLE
Editionsrichtlinien fehlen

### ISSUE THREAD

**Issue by rettinghaus** [pfefferniels/probstuecke-digital#4]

**Comment by pfefferniels** [comment]
For now the practise has been:

- All the original clefs are preserved, since it's possible to replace them automatically with modern clefs but not vice versa
- Accidentals are adapted to modern use 
- obvious and clear mistakes are corrected tacitly
- The text is generally preserved in its original orthography, including the different letter-spacing. But for the sake of easier readability all `/ ` are replaced by `,`

Any additions/comments?

**Comment by rettinghaus** [comment]
* The long s (`ſ`) has been normalized
* Linebreaks are not preserved (To be discussed)
* Musical meters in the text are encoded using a `/`

**Comment by pfefferniels** [comment]
See a5c3785ed8d6a35868bc169f07e40e889087fd2e

**Comment by rettinghaus** [comment]
The Gothic print does not distinguish between I and J. Should we follow the DTA guidelines or leave it like it is and just document this decision?

**Comment by pfefferniels** [comment]
Guidelines, although still more a sort of draft, do exist meanwhile.
